services:
  api:
    image: bankapi:${TAG:-latest}
    container_name: bankapi-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GO_ENV=production
      tags:
        - "bankapi:${TAG:-latest}"
        - "bankapi:latest"
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DATABASE=${MONGO_DATABASE:-bankdb}
      - MONGO_COLLECTION=${MONGO_COLLECTION:-banks}
      - API_SERVER_PORT=:8080
    volumes:
      - ./.env:/app/.env:ro
    depends_on:
      - mongodb
    networks:
      - bank-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: bankapi-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - bank-network
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE:-bankdb}

networks:
  bank-network:
    name: bankapi-network
    driver: bridge

volumes:
  mongodb_data:
    name: bankapi-mongodb-data
