services:
  api:
    image: bankapi:${TAG:-latest}
    container_name: bankapi-service
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - GO_ENV=${GO_ENV:-production}
    ports:
      - "${API_PORT:-8080}:8080"
    env_file:
      - ../.env
    environment:
      - MONGO_URI=${MONGO_URI:-mongodb://mongodb:27017}
      - MONGO_DATABASE=${MONGO_DATABASE:-bank_db}
      - MONGO_COLLECTION=${MONGO_COLLECTION:-banks}
      - API_SERVER_PORT=${API_SERVER_PORT:-:8080}
      - SPREADSHEET_ID=${SPREADSHEET_ID:-1iFFqsu_xruvVKzXAadAAlDBpIuU51v-pfIEU5HeGa8w}
    depends_on:
      - mongodb
    networks:
      - bank-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: bankapi-mongodb
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - bank-network
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE:-bank_db}

networks:
  bank-network:
    name: bankapi-network
    driver: bridge

volumes:
  mongodb_data:
    name: bankapi-mongodb-data
